export const GEOLOCATION = 'GEOLOCATION';

export const CURRENT_WEATHER_SUCCESS = 'CURRENT_WEATHER_SUCCESS';

export const FORECAST_12_SUCCESS = 'FORECAST_12_SUCCESS';

export const FORECAST_5_SUCCESS = 'FORECAST_5_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const CELSIUS = 'CELSIUS';

export const PERSONAL_DATA_TOGGLE = 'PERSONAL_DATA_TOGGLE';

export const PERSONAL_DATA_RESET = 'PERSONAL_DATA_RESET';

export const FIRST_PERSONAL_DATA_AUTO_FETCH_SUCCESS = 'FIRST_PERSONAL_DATA_AUTO_FETCH_SUCCESS';

export const PERSONAL_INFO_FETCH_SUCCESS = 'PERSONAL_INFO_FETCH_SUCCESS';

export const PERSONAL_DATA_LOADED = 'PERSONAL_DATA_LOADED' 

export const SET_LOCALID_IDTOKEN  = 'SET_LOCALID_IDTOKEN' 